Update composer to pull in theme dependencies
atfweb/prudentia pull request #1
Opened 2021-04-02 14:41 UTC by sarahjean

This PR adds the components module and usdws_base to the composer file so that when `composer require atf/prudentia` is called, the base theme and components module will be pulled into their respective contrib folders without running additional commands. It also adds 'components' to the prudentia dependencies so that it needs to be turned on to enable the theme.

2021-04-05 15:54 UTC, RoyaRRateshtari requested changes
The following item under section **Important Notes**  needs to be removed:

"- You need to install/enable **Components Library** Drupal module (https://www.drupal.org/project/components) to use the Prudentia components."

2021-04-05 16:03 UTC, sarahjean commented
@RoyaRRateshtari There is a small distinction here, it might need to be phrased a different way to be clear. Adding Components to the composer file pulls the module to modules/contrib/components, but theme module dependencies seem to work differently than module dependencies. In the case of module dependencies enabling a module enables its dependencies, but it seems when a theme depends on a module you can't enable the theme unless the module is enabled. If you do a test locally you will see a message about it under the theme in the Appearance tab.

How about this adjustment?:

```
- The Prudentia theme depends on the Components Library Drupal module (https://www.drupal.org/project/components) and the module must be enabled to enable the theme. If you install the theme via composer the module will be pulled into your codebase automatically."
```

2021-04-05 23:30 UTC, RoyaRRateshtari commented
**@sarahjean:** I am ok with your adjustment. Thanks!

2021-04-06 18:18 UTC, sarahjean commented
@RoyaRRateshtari Updated the readme text per discussion.

2021-04-08 15:52 UTC, mayelaatf reviewed
@sarahjean 
The code on this pull request looks fine, however, the branch name does not follow our branch name convention.
It should be: pru-ticket#-developerinitials
Please update, thanks

2021-04-08 17:04 UTC, closed without merging